# Generated by Django 2.1.7 on 2019-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='hobbies',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='race',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
